# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:12:14+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class DeleteEventsResponse(BaseModel):
    pass


class ResolutionStatus(Enum):
    RESOLUTION_STATUS_UNSPECIFIED = 'RESOLUTION_STATUS_UNSPECIFIED'
    OPEN = 'OPEN'
    ACKNOWLEDGED = 'ACKNOWLEDGED'
    RESOLVED = 'RESOLVED'
    MUTED = 'MUTED'


class HttpRequestContext(BaseModel):
    method: Optional[str] = Field(
        None, description='The type of HTTP request, such as `GET`, `POST`, etc.'
    )
    referrer: Optional[str] = Field(
        None, description='The referrer information that is provided with the request.'
    )
    remoteIp: Optional[str] = Field(
        None,
        description='The IP address from which the request originated. This can be IPv4, IPv6, or a token which is derived from the IP address, depending on the data that has been provided in the error report.',
    )
    responseStatusCode: Optional[int] = Field(
        None, description='The HTTP response status code for the request.'
    )
    url: Optional[str] = Field(None, description='The URL of the request.')
    userAgent: Optional[str] = Field(
        None,
        description='The user agent information that is provided with the request.',
    )


class ReportErrorEventResponse(BaseModel):
    pass


class ServiceContext(BaseModel):
    resourceType: Optional[str] = Field(
        None,
        description='Type of the MonitoredResource. List of possible values: https://cloud.google.com/monitoring/api/resources Value is set automatically for incoming errors and must not be set when reporting errors.',
    )
    service: Optional[str] = Field(
        None,
        description='An identifier of the service, such as the name of the executable, job, or Google App Engine service name. This field is expected to have a low number of values that are relatively stable over time, as opposed to `version`, which can be changed whenever new code is deployed. Contains the service name for error reports extracted from Google App Engine logs or `default` if the App Engine default service is used.',
    )
    version: Optional[str] = Field(
        None,
        description='Represents the source code version that the developer provided, which could represent a version label or a Git SHA-1 hash, for example. For App Engine standard environment, the version is set to the version of the app.',
    )


class SourceLocation(BaseModel):
    filePath: Optional[str] = Field(
        None,
        description='The source code filename, which can include a truncated relative path, or a full path from a production machine.',
    )
    functionName: Optional[str] = Field(
        None,
        description='Human-readable name of a function or method. The value can include optional context like the class or package name. For example, `my.package.MyClass.method` in case of Java.',
    )
    lineNumber: Optional[int] = Field(
        None, description='1-based. 0 indicates that the line number is unknown.'
    )


class SourceReference(BaseModel):
    repository: Optional[str] = Field(
        None,
        description='Optional. A URI string identifying the repository. Example: "https://github.com/GoogleCloudPlatform/kubernetes.git"',
    )
    revisionId: Optional[str] = Field(
        None,
        description='The canonical and persistent identifier of the deployed revision. Example (git): "0035781c50ec7aa23385dc841529ce8a4b70db1b"',
    )


class TimedCount(BaseModel):
    count: Optional[str] = Field(
        None, description='Approximate number of occurrences in the given time period.'
    )
    endTime: Optional[str] = Field(
        None, description='End of the time period to which `count` refers (excluded).'
    )
    startTime: Optional[str] = Field(
        None, description='Start of the time period to which `count` refers (included).'
    )


class TrackingIssue(BaseModel):
    url: Optional[str] = Field(
        None,
        description='A URL pointing to a related entry in an issue tracking system. Example: `https://github.com/user/project/issues/4`',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class TimeRangePeriod(Enum):
    PERIOD_UNSPECIFIED = 'PERIOD_UNSPECIFIED'
    PERIOD_1_HOUR = 'PERIOD_1_HOUR'
    PERIOD_6_HOURS = 'PERIOD_6_HOURS'
    PERIOD_1_DAY = 'PERIOD_1_DAY'
    PERIOD_1_WEEK = 'PERIOD_1_WEEK'
    PERIOD_30_DAYS = 'PERIOD_30_DAYS'


class Alignment(Enum):
    ERROR_COUNT_ALIGNMENT_UNSPECIFIED = 'ERROR_COUNT_ALIGNMENT_UNSPECIFIED'
    ALIGNMENT_EQUAL_ROUNDED = 'ALIGNMENT_EQUAL_ROUNDED'
    ALIGNMENT_EQUAL_AT_END = 'ALIGNMENT_EQUAL_AT_END'


class Order(Enum):
    GROUP_ORDER_UNSPECIFIED = 'GROUP_ORDER_UNSPECIFIED'
    COUNT_DESC = 'COUNT_DESC'
    LAST_SEEN_DESC = 'LAST_SEEN_DESC'
    CREATED_DESC = 'CREATED_DESC'
    AFFECTED_USERS_DESC = 'AFFECTED_USERS_DESC'


class GroupId(RootModel[List[str]]):
    root: List[str]


class ErrorContext(BaseModel):
    httpRequest: Optional[HttpRequestContext] = Field(
        None,
        description='The HTTP request which was processed when the error was triggered.',
    )
    reportLocation: Optional[SourceLocation] = Field(
        None,
        description='The location in the source code where the decision was made to report the error, usually the place where it was logged. For a logged exception this would be the source line where the exception is logged, usually close to the place where it was caught.',
    )
    sourceReferences: Optional[List[SourceReference]] = Field(
        None,
        description='Source code that was used to build the executable which has caused the given error message.',
    )
    user: Optional[str] = Field(
        None,
        description='The user who caused or was affected by the crash. This can be a user ID, an email address, or an arbitrary token that uniquely identifies the user. When sending an error report, leave this field empty if the user was not logged in. In this case the Error Reporting system will use other data, such as remote IP address, to distinguish affected users. See `affected_users_count` in `ErrorGroupStats`.',
    )


class ErrorEvent(BaseModel):
    context: Optional[ErrorContext] = Field(
        None, description='Data about the context in which the error occurred.'
    )
    eventTime: Optional[str] = Field(
        None,
        description='Time when the event occurred as provided in the error report. If the report did not contain a timestamp, the time the error was received by the Error Reporting system is used.',
    )
    message: Optional[str] = Field(
        None, description='The stack trace that was reported or logged by the service.'
    )
    serviceContext: Optional[ServiceContext] = Field(
        None, description='The `ServiceContext` for which this error was reported.'
    )


class ErrorGroup(BaseModel):
    groupId: Optional[str] = Field(
        None,
        description='Group IDs are unique for a given project. If the same kind of error occurs in different service contexts, it will receive the same group ID.',
    )
    name: Optional[str] = Field(
        None,
        description='The group resource name. Example: projects/my-project-123/groups/CNSgkpnppqKCUw',
    )
    resolutionStatus: Optional[ResolutionStatus] = Field(
        None,
        description="Error group's resolution status. An unspecified resolution status will be interpreted as OPEN",
    )
    trackingIssues: Optional[List[TrackingIssue]] = Field(
        None, description='Associated tracking issues.'
    )


class ErrorGroupStats(BaseModel):
    affectedServices: Optional[List[ServiceContext]] = Field(
        None,
        description='Service contexts with a non-zero error count for the given filter criteria. This list can be truncated if multiple services are affected. Refer to `num_affected_services` for the total count.',
    )
    affectedUsersCount: Optional[str] = Field(
        None,
        description='Approximate number of affected users in the given group that match the filter criteria. Users are distinguished by data in the ErrorContext of the individual error events, such as their login name or their remote IP address in case of HTTP requests. The number of affected users can be zero even if the number of errors is non-zero if no data was provided from which the affected user could be deduced. Users are counted based on data in the request context that was provided in the error report. If more users are implicitly affected, such as due to a crash of the whole service, this is not reflected here.',
    )
    count: Optional[str] = Field(
        None,
        description='Approximate total number of events in the given group that match the filter criteria.',
    )
    firstSeenTime: Optional[str] = Field(
        None,
        description='Approximate first occurrence that was ever seen for this group and which matches the given filter criteria, ignoring the time_range that was specified in the request.',
    )
    group: Optional[ErrorGroup] = Field(
        None, description='Group data that is independent of the filter criteria.'
    )
    lastSeenTime: Optional[str] = Field(
        None,
        description='Approximate last occurrence that was ever seen for this group and which matches the given filter criteria, ignoring the time_range that was specified in the request.',
    )
    numAffectedServices: Optional[int] = Field(
        None,
        description='The total number of services with a non-zero error count for the given filter criteria.',
    )
    representative: Optional[ErrorEvent] = Field(
        None,
        description='An arbitrary event that is chosen as representative for the whole group. The representative event is intended to be used as a quick preview for the whole group. Events in the group are usually sufficiently similar to each other such that showing an arbitrary representative provides insight into the characteristics of the group as a whole.',
    )
    timedCounts: Optional[List[TimedCount]] = Field(
        None,
        description='Approximate number of occurrences over time. Timed counts returned by ListGroups are guaranteed to be: - Inside the requested time interval - Non-overlapping, and - Ordered by ascending time.',
    )


class ListEventsResponse(BaseModel):
    errorEvents: Optional[List[ErrorEvent]] = Field(
        None, description='The error events which match the given request.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='If non-empty, more results are available. Pass this token, along with the same query parameters as the first request, to view the next page of results.',
    )
    timeRangeBegin: Optional[str] = Field(
        None,
        description='The timestamp specifies the start time to which the request was restricted.',
    )


class ListGroupStatsResponse(BaseModel):
    errorGroupStats: Optional[List[ErrorGroupStats]] = Field(
        None, description='The error group stats which match the given request.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='If non-empty, more results are available. Pass this token, along with the same query parameters as the first request, to view the next page of results.',
    )
    timeRangeBegin: Optional[str] = Field(
        None,
        description='The timestamp specifies the start time to which the request was restricted. The start time is set based on the requested time range. It may be adjusted to a later time if a project has exceeded the storage quota and older data has been deleted.',
    )


class ReportedErrorEvent(BaseModel):
    context: Optional[ErrorContext] = Field(
        None,
        description='Optional. A description of the context in which the error occurred.',
    )
    eventTime: Optional[str] = Field(
        None,
        description='Optional. Time when the event occurred. If not provided, the time when the event was received by the Error Reporting system is used. If provided, the time must not exceed the [logs retention period](https://cloud.google.com/logging/quotas#logs_retention_periods) in the past, or be more than 24 hours in the future. If an invalid time is provided, then an error is returned.',
    )
    message: Optional[str] = Field(
        None,
        description='Required. The error message. If no `context.reportLocation` is provided, the message must contain a header (typically consisting of the exception type name and an error message) and an exception stack trace in one of the supported programming languages and formats. Supported languages are Java, Python, JavaScript, Ruby, C#, PHP, and Go. Supported stack trace formats are: * **Java**: Must be the return value of [`Throwable.printStackTrace()`](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#printStackTrace%28%29). * **Python**: Must be the return value of [`traceback.format_exc()`](https://docs.python.org/2/library/traceback.html#traceback.format_exc). * **JavaScript**: Must be the value of [`error.stack`](https://github.com/v8/v8/wiki/Stack-Trace-API) as returned by V8. * **Ruby**: Must contain frames returned by [`Exception.backtrace`](https://ruby-doc.org/core-2.2.0/Exception.html#method-i-backtrace). * **C#**: Must be the return value of [`Exception.ToString()`](https://msdn.microsoft.com/en-us/library/system.exception.tostring.aspx). * **PHP**: Must be prefixed with `"PHP (Notice|Parse error|Fatal error|Warning): "` and contain the result of [`(string)$exception`](https://php.net/manual/en/exception.tostring.php). * **Go**: Must be the return value of [`runtime.Stack()`](https://golang.org/pkg/runtime/debug/#Stack).',
    )
    serviceContext: Optional[ServiceContext] = Field(
        None,
        description='Required. The service context in which this error has occurred.',
    )
